# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Storm Project.
#
# storm-workbench is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '3.2'

services:
  research-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: stormproject/pkg-fmask:0.1
    container_name: pkg-fmask
    tty: true
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
    restart: on-failure
