name: fmask
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- blosc=1.21.1
- boost-cpp=1.78.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.9.24
- cairo=1.16.0
- cfitsio=4.1.0
- curl=7.86.0
- expat=2.5.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.1
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- freetype=2.12.1
- freexl=1.0.6
- gdal=3.5.3
- geos=3.11.0
- geotiff=1.7.1
- gettext=0.21.1
- giflib=5.2.1
- hdf4=4.2.15
- hdf5=1.12.2
- icu=70.1
- jpeg=9e
- json-c=0.16
- kealib=1.4.15
- keyutils=1.6.1
- krb5=1.19.3
- lcms2=2.14
- ld_impl_linux-64=2.39
- lerc=4.0.0
- libblas=3.9.0
- libcblas=3.9.0
- libcurl=7.86.0
- libdap4=3.20.6
- libdeflate=1.14
- libedit=3.1.20191231
- libev=4.33
- libffi=3.4.2
- libgcc-ng=12.2.0
- libgdal=3.5.3
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libglib=2.74.1
- libgomp=12.2.0
- libiconv=1.17
- libkml=1.3.0
- liblapack=3.9.0
- libnetcdf=4.8.1
- libnghttp2=1.47.0
- libnsl=2.0.0
- libopenblas=0.3.21
- libpng=1.6.38
- libpq=14.5
- librttopo=1.1.0
- libspatialite=5.0.1
- libsqlite=3.39.4
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libtiff=4.4.0
- libuuid=2.32.1
- libwebp-base=1.2.4
- libxcb=1.13
- libxml2=2.10.3
- libzip=1.9.2
- libzlib=1.2.13
- lz4-c=1.9.3
- ncurses=6.3
- nspr=4.32
- nss=3.78
- numpy=1.23.4
- openjpeg=2.5.0
- openssl=3.0.7
- pcre=8.45
- pcre2=10.40
- pip=22.3.1
- pixman=0.40.0
- poppler=22.11.0
- poppler-data=0.4.11
- postgresql=14.5
- proj=9.1.0
- pthread-stubs=0.4
- python=3.8.13
- python-fmask=0.5.7
- python_abi=3.8
- readline=8.1.2
- rios=1.4.12
- scipy=1.9.3
- setuptools=65.5.1
- snappy=1.1.9
- sqlite=3.39.4
- tiledb=2.11.3
- tk=8.6.12
- tzcode=2022f
- tzdata=2022f
- wheel=0.38.4
- xerces-c=3.2.4
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.6
- zlib=1.2.13
- zstd=1.5.2
